api = "0.7"

[buildpack]
id = "be.rossel.tech.orchestrion"
version = "1.0.0"
name = "Datadog Orchestrion Installer"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
[[stacks]]
id = "io.buildpacks.stacks.jammy"
