name: Dependabot Configuration
on:
  schedule:
    - cron: "0 4 * * *" # Daily at midnight
  workflow_dispatch: # Manual trigger for testing
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dependabot-gen.yaml"
permissions:
  contents: write
  id-token: write
  pull-requests: write
  issues: read
  checks: write
jobs:
  generate-dependabot:
    if: ${{ !endsWith(github.repository, '-goldenstack') }}
    uses: groupe-rossel/tech-cloud-github-reusable-workflows/.github/workflows/auto-generate-dependabot.yaml@stable
    with:
      repository_name: ${{ github.event.repository.name }}
    secrets:
      GH_INIT_TPL_APP_ID: ${{ secrets.GH_INIT_TPL_APP_ID }}
      GH_INIT_TPL_APP_PRIVATE_KEY: ${{ secrets.GH_INIT_TPL_APP_PRIVATE_KEY }}
